<<<<<<< HEAD
# Generated by Django 5.0.7 on 2025-03-28 11:33
=======
# Generated by Django 5.1.7 on 2025-03-28 13:00
>>>>>>> aboba

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 11, 33, 21, 899751, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 0, 10, 666436, tzinfo=datetime.timezone.utc)),
>>>>>>> aboba
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 11, 33, 21, 898748, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 0, 10, 666436, tzinfo=datetime.timezone.utc)),
>>>>>>> aboba
        ),
    ]
