# Generated by Django 5.1.7 on 2025-03-28 15:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='DoB',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='Pan',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='image',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='ob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 15, 30, 41, 118091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 15, 30, 41, 118091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='aadhaar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('business', 'Business')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='pan',
            field=models.CharField(default='NOT_PROVIDED', max_length=20, verbose_name='PAN Number'),
        ),
    ]
